/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_huangjie_demo10pressure2_MainActivity */

#ifndef _Included_com_huangjie_demo10pressure2_MainActivity
#define _Included_com_huangjie_demo10pressure2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_huangjie_demo10pressure2_MainActivity
 * Method:    startMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huangjie_demo10pressure2_MainActivity_startMonitor
  (JNIEnv *, jobject);

/*
 * Class:     com_huangjie_demo10pressure2_MainActivity
 * Method:    stopMonitor
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_huangjie_demo10pressure2_MainActivity_stopMonitor
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
